### ISSUE TITLE
Analyze CTS role interview data

### ISSUE THREAD

**Issue by saragon02** [data2health/CTS-Personas#10]

**Comment by jmcmurry** [comment]
Related: If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by saragon02** [comment]
Machine transcription test by Meen: https://docs.google.com/document/d/1EoXuEOK40W53UlxZsQzGdKpsM2HLNurqe2SFyoIpHO8/edit?usp=sharing
