### ISSUE TITLE
IRB and consents

### ISSUE THREAD

**Issue by saragon02** [data2health/CTS-Personas#22]

**Comment by tatianapatton** [comment]
CHOP will need a copy of the consent document, the list of questions, the completed IRB application from Northwestern, and the approved IRB letter from Northwestern before CHOP can submit to the IRB and have Northwestern the IRB of record.

**Comment by tatianapatton** [comment]
We also need to know who will be the PI on the CHOP side.

**Comment by saragon02** [comment]
> 
> 
> We also need to know who will be the PI on the CHOP side.

Tatiana, @allisonheath, @baileyckelly, I wanted to update you all to let you know that I have just received an exemption determination from Northwestern IRB for the Personas Interview Project. This means that Northwestern will not serve as the IRB of record for the interviews. If you plan to conduct interviews as part of the project, CHOP will need to do its own internal IRB application. Please let me know if you will still require a copy of the NU IRB application for the project.
