### ISSUE TITLE
Look at personas on The Gravity Project

### ISSUE THREAD

**Issue by kristiholmes** [data2health/CTS-Personas#29]
https://sirenetwork.ucsf.edu/TheGravityProject 

what is overlap (confirmation), what is new? It would be good to get a better understanding of our work in the context of this persona effort. Thanks!

**Comment by saragon02** [comment]
Personas are currently being submitted to the Gravity Project for inclusion in their Use Case package. Their worksheet asks the following questions (credit: https://confluence.hl7.org/display/PC/Gravity+Personas)

    Name
    Role
    Age
    Qualifications/Specialties (if a practitioner)
    What organization working for (if a practioner)
    About the Persona
        Brief description of persona. What is their profession? What is their history with health and social conditions identified? Are they married, divorced? How many children? Do they live with them? What are activities they are currently engaged in? What worries them about their existing conditions or situation? What are their preferences and needs?
    Clinical Health Concern
    Social Risk Factors
    Typical routine and interactions
        What does a regular day look like and include?
    Challenges and Goals
        What are the primary challenges faced at the most recent point in time?
    What the persona wants from the health system

**Comment by kristiholmes** [comment]
Sounds great, thanks, Sara!
