### ISSUE TITLE
Create evaluation measures

### ISSUE THREAD

**Issue by saragon02** [data2health/CTS-Personas#3]
Release Personas one-pagers and documentation to the CD2H community and evaluate effectiveness through survey instruments.

**Comment by mellybelly** [comment]
@saragon02 can you add some descriptions to this one? I know you probably have a library of things here ;-). 

One thing I might suggest is that we consider, similar to requirements, that evaluation measures also include thematic areas of data, software, people, edu.

**Comment by saragon02** [comment]
Survey questions on 5-point Likert scale (1= strongly disagree; 5= strongly agree). Running list of questions:

1. The CTS persona profiles are clear and representative for several roles supporting clinical and translational science.
2. The CTS persona profiles are useful for the development of use cases
3. The CTS persona profiles are useful for the development of communications materials 
4. The CTS persona profiles are useful for the development of training and educational materials 
5. The CTS persona profiles are useful for the development of software
6. The CTS persona profiles are useful for the development of data management and storage solutions

**Comment by saragon02** [comment]
Personas evaluation completed: https://docs.google.com/forms/d/e/1FAIpQLSc0PiMqi12YVz9SvdHNqUocwgz8KKHOKdj3NQ80xJmMNyR_oA/viewform?usp=sf_link
