### ISSUE TITLE
Add clearer link to working personas on repo landing page

### ISSUE THREAD

**Issue by mellybelly** [data2health/CTS-Personas#30]
Where the personas documents are located is not clear at present. Are the personas intended to be kept current by the community? Can the library of personas be extended by the community? If so we will need better exposure and guidance on how to contribute.

**Comment by saragon02** [comment]
Thanks, Melissa! A direct link to the Working Personas Profiles has been added to the Working Personas Profiles folder on the landing page. I'll also include the link here: https://drive.google.com/drive/folders/1-mNCKZ7IbnBxRySPNAMPFrjoeG9C4ObW?usp=sharing
