### ISSUE TITLE
create space for community commentary and contribution

### ISSUE THREAD

**Issue by mellybelly** [data2health/CTS-Personas#31]
as per convo w @kristiholmes, it would be terrific to have each persona have a living documentation space where community members can contribute attributes to them or make suggestions. Also would be good for folks to be able to add new personas.

**Comment by saragon02** [comment]
CTS-Personas GitHub remains live for documentation. Procedure for creating new Personas is documented on the io Methodology page: https://data2health.github.io/CTS-Personas/pages/methodology/methodology.html
