### ISSUE TITLE
Add computable elements

### ISSUE THREAD

**Issue by mellybelly** [data2health/CTS-Personas#32]
As per convo w @kristiholmes, it would be terrific if there were computable attributes for each persona. For example, the use/creation of data, software or tools, and expertise. Examples obtained during the interviews are a great start, and may also be nice visual guides as well.

**Comment by saragon02** [comment]
Issue on hold. Work is beyond scope of Phase II Personas; pending to determine if Phase III work is possible.

**Comment by kristiholmes** [comment]
Per comment above, closing ticket and holding this as potential work for Phase 3.

> Issue on hold. Work is beyond scope of Phase II Personas; pending to determine if Phase III work is possible.
