### ISSUE TITLE
consider listing personas on the main home page

### ISSUE THREAD

**Issue by clarkevans** [data2health/CTS-Personas#38]
It took me some time before I was able to find the personas [1].  Given that it's a simple list with DOIs, perhaps the best place for the final output work is in your README where it would be front and center. This is a great resource.  Thanks.

[1] https://github.com/data2health/CTS-Personas/blob/master/Profiles%20Documents/Profiles_2019_09_09.md

**Comment by LisaOKeefe1** [comment]
thank you @clarkevans! e really appreciate the feedback. I'll share this with Sara, too.
