### ISSUE TITLE
Template available for additional persona profile development

### ISSUE THREAD

**Issue by DaveraGabriel** [data2health/CTS-Personas#39]
Following-up on utilization of profiles for user story development for HOT, a template or editable version of the profile standard would support development of draft additional profiles

**Comment by LisaOKeefe1** [comment]
Hi @DaveraGabriel, we really appreciate your feedback and interest in our Personas work. You can refer to our user guidebook (link below) a key to our persona profile layout, a key to our icons and more.  

Thanks again for your contributions to this work!

https://digitalhub.northwestern.edu/files/86c74821-e12c-4263-b33a-d005870505a5

**Comment by kristiholmes** [comment]
- PowerPoint template that can be used for any persona you wish to create: https://github.com/data2health/CTS-Personas/blob/master/Profiles%20Documents/template_PersonaProfile(Biostatistician).pptx?raw=true
- Personas document folder: https://github.com/data2health/CTS-Personas/tree/master/Profiles%20Documents
- Methodology: https://data2health.github.io/CTS-Personas/pages/methodology/methodology.html
