### ISSUE TITLE
Create CTS Employee Persona Template

### ISSUE THREAD

**Issue by saragon02** [data2health/CTS-Personas#4]
Remember to keep in mind the overall needs that the Personas project as a whole will address:

- Data
- Functionality and workflows; UX
- Professional development/Training (job training, leadership training, mentorship training, etc.)
- Access to resources
- Team science (and credit/attribution for same)

**Comment by mellybelly** [comment]
Also consider what types of data, software, expertise, having real examples very helpful!

**Comment by saragon02** [comment]
CTS Employee Persona Template completed. See Google Doc: https://docs.google.com/document/d/1weUPuMWk8TE_1Y4Dr_cpj37NTtKaKGp8pSA6NkChcsQ/edit?usp=sharing
