### ISSUE TITLE
Evaluation of Personas understandability & impact

### ISSUE THREAD

**Issue by jmcmurry** [data2health/CTS-Personas#45]
Evaluation of the [survey](https://docs.google.com/forms/d/e/1FAIpQLSc0PiMqi12YVz9SvdHNqUocwgz8KKHOKdj3NQ80xJmMNyR_oA/viewform) response (launched 10/11/2019) and other feedback mechanisms.
According to RPPR this is Due Dec 24

**Comment by kristiholmes** [comment]
complete - please see https://docs.google.com/document/d/15yanFJMDa6emtoe1JI3X8lfipiNrXBTlHAtIg3bEftQ/edit?ts=5dfbd192

**Comment by jmcmurry** [comment]
Please file that doc in the CD2H folder and make viewable by cd2h-allhands, thanks
