### ISSUE TITLE
Interview questions for role representatives

### ISSUE THREAD

**Issue by saragon02** [data2health/CTS-Personas#5]
CHOP to share interview questions from previous Personas work. All project participants to provide additional questions from the Personas literature to this Google folder: https://drive.google.com/drive/folders/171DqzCClw7Bn_cM4XQ_lsJnri9FkjALh?usp=sharing

**Comment by mellybelly** [comment]
@saragon02 should there be corresponding tickets for identifying the interviewees and analyzing the interview data?

**Comment by saragon02** [comment]
Yes, thanks Melissa!

**Comment by baileyckelly** [comment]
Uploaded our list of questions from our Cohort Builder interviews to the google drive!

**Comment by LisaOKeefe1** [comment]
Hi @saragon02 are there plans to write an interview protocol or guide for our interviewers? This might help us to stay consistent and alleviate anxiety for our interviewers, get the best information during interviews. If this is something we need to do, am happy to help!

**Comment by saragon02** [comment]
We definitely need to write an interview protocol or script. Volunteers for this effort are much appreciated!

**Comment by saragon02** [comment]
Working Doc: Interview Consent and Script: https://docs.google.com/document/d/19DfWFGqObT8Tb7E1-3V7yqWqzUZsHiD5jKqZ9PpWi8E/edit?usp=sharing
