### ISSUE TITLE
Grouping of CTS roles

### ISSUE THREAD

**Issue by saragon02** [data2health/CTS-Personas#7]
Group CTS roles according to job families to allow a quick assessment of where the roles are falling. If we can ensure all families are represented, we can choose a select amount of roles for our batch of Personas.

**Comment by saragon02** [comment]
**CTS Job Families**

**Basic Science Research**
Faculty Investigator
Jr. Faculty Investigator


**Clinical Research**
Clinical Operations Manager
Clinical Research Coordinator
Clinical Research Nurse
Clinical Research Project Manager
Research Administrator
Research Study Coordinator
Research Study Recruitment Coordinator
Faculty Investigator
Jr. Faculty Investigator
Graduate Student
Data Analyst
Data Curator
Evaluator
Project Manager


**Grants**
Grant Officer
Research Administrator
Database Coordinator


**Digital Systems**
Developer
Systems Analyst


**University Support**
Data Warehouse Administrator
Librarian


**Administration**
Center/Program Administrator


**Public Health**
Clinician
Patient
Caregiver
Social Worker

**Comment by saragon02** [comment]
Add to this list from our Google Sheet of CTSA Org Charts (https://docs.google.com/spreadsheets/d/1-2Sv_jHywQh3p75GjxiPKtxbex98oggFcvDQ-eyHJXQ/edit?usp=sharing). Feel free to contribute additional links to the spreadsheet.

**Comment by kristiholmes** [comment]
we may want to include terms to reflect the community, such as 
Community Partner
Community-Engaged Researcher
Patient Advocate
Public Health Official

**Comment by saragon02** [comment]
See (and please feel free to add to) resource documents here: https://drive.google.com/drive/folders/1-HaAZvToKJFtU3dd4CmvXPW7Maoz2R5U?usp=sharing
